/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PortfolioAttestation {
  export type AttestationStruct = {
    blockNumber: BigNumberish;
    merkleRoot: BytesLike;
    totalValueGun: BigNumberish;
    itemCount: BigNumberish;
    timestamp: BigNumberish;
    metadataURI: string;
  };

  export type AttestationStructOutput = [
    blockNumber: bigint,
    merkleRoot: string,
    totalValueGun: bigint,
    itemCount: bigint,
    timestamp: bigint,
    metadataURI: string
  ] & {
    blockNumber: bigint;
    merkleRoot: string;
    totalValueGun: bigint;
    itemCount: bigint;
    timestamp: bigint;
    metadataURI: string;
  };
}

export interface PortfolioAttestationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "attest"
      | "attestFee"
      | "getAttestation"
      | "getAttestationCount"
      | "getLatestAttestation"
      | "initialize"
      | "owner"
      | "proxiableUUID"
      | "setFee"
      | "totalAttestations"
      | "totalFeesCollected"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "verifyHolding"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "Initialized"
      | "OwnerTransferred"
      | "PortfolioAttested"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attest",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "attestFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAttestations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHolding",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "attestFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyHolding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PortfolioAttestedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    attestationId: BigNumberish,
    merkleRoot: BytesLike,
    totalValueGun: BigNumberish,
    itemCount: BigNumberish,
    blockNumber: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    wallet: string,
    attestationId: bigint,
    merkleRoot: string,
    totalValueGun: bigint,
    itemCount: bigint,
    blockNumber: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    wallet: string;
    attestationId: bigint;
    merkleRoot: string;
    totalValueGun: bigint;
    itemCount: bigint;
    blockNumber: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PortfolioAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): PortfolioAttestation;
  waitForDeployment(): Promise<this>;

  interface: PortfolioAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  attest: TypedContractMethod<
    [
      wallet: AddressLike,
      blockNumber: BigNumberish,
      merkleRoot: BytesLike,
      totalValueGun: BigNumberish,
      itemCount: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "payable"
  >;

  attestFee: TypedContractMethod<[], [bigint], "view">;

  getAttestation: TypedContractMethod<
    [wallet: AddressLike, index: BigNumberish],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;

  getAttestationCount: TypedContractMethod<
    [wallet: AddressLike],
    [bigint],
    "view"
  >;

  getLatestAttestation: TypedContractMethod<
    [wallet: AddressLike],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<
    [_attestFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  setFee: TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;

  totalAttestations: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verifyHolding: TypedContractMethod<
    [
      wallet: AddressLike,
      attestationIndex: BigNumberish,
      leaf: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      blockNumber: BigNumberish,
      merkleRoot: BytesLike,
      totalValueGun: BigNumberish,
      itemCount: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "attestFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [wallet: AddressLike, index: BigNumberish],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestationCount"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestAttestation"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_attestFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAttestations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verifyHolding"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      attestationIndex: BigNumberish,
      leaf: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerTransferred"
  ): TypedContractEvent<
    OwnerTransferredEvent.InputTuple,
    OwnerTransferredEvent.OutputTuple,
    OwnerTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PortfolioAttested"
  ): TypedContractEvent<
    PortfolioAttestedEvent.InputTuple,
    PortfolioAttestedEvent.OutputTuple,
    PortfolioAttestedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnerTransferred(address,address)": TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;
    OwnerTransferred: TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;

    "PortfolioAttested(address,uint256,bytes32,uint256,uint16,uint256,string)": TypedContractEvent<
      PortfolioAttestedEvent.InputTuple,
      PortfolioAttestedEvent.OutputTuple,
      PortfolioAttestedEvent.OutputObject
    >;
    PortfolioAttested: TypedContractEvent<
      PortfolioAttestedEvent.InputTuple,
      PortfolioAttestedEvent.OutputTuple,
      PortfolioAttestedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
