/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PortfolioAttestation {
  export type AttestationStruct = {
    blockNumber: BigNumberish;
    merkleRoot: BytesLike;
    totalValueGun: BigNumberish;
    itemCount: BigNumberish;
    timestamp: BigNumberish;
    metadataURI: string;
  };

  export type AttestationStructOutput = [
    blockNumber: bigint,
    merkleRoot: string,
    totalValueGun: bigint,
    itemCount: bigint,
    timestamp: bigint,
    metadataURI: string
  ] & {
    blockNumber: bigint;
    merkleRoot: string;
    totalValueGun: bigint;
    itemCount: bigint;
    timestamp: bigint;
    metadataURI: string;
  };
}

export interface PortfolioAttestationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attest"
      | "getAttestation"
      | "getAttestationCount"
      | "getLatestAttestation"
      | "totalAttestations"
      | "verifyHolding"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PortfolioAttested"): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAttestations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHolding",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyHolding",
    data: BytesLike
  ): Result;
}

export namespace PortfolioAttestedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    attestationId: BigNumberish,
    merkleRoot: BytesLike,
    totalValueGun: BigNumberish,
    itemCount: BigNumberish,
    blockNumber: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    wallet: string,
    attestationId: bigint,
    merkleRoot: string,
    totalValueGun: bigint,
    itemCount: bigint,
    blockNumber: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    wallet: string;
    attestationId: bigint;
    merkleRoot: string;
    totalValueGun: bigint;
    itemCount: bigint;
    blockNumber: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PortfolioAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): PortfolioAttestation;
  waitForDeployment(): Promise<this>;

  interface: PortfolioAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [
      blockNumber: BigNumberish,
      merkleRoot: BytesLike,
      totalValueGun: BigNumberish,
      itemCount: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  getAttestation: TypedContractMethod<
    [wallet: AddressLike, index: BigNumberish],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;

  getAttestationCount: TypedContractMethod<
    [wallet: AddressLike],
    [bigint],
    "view"
  >;

  getLatestAttestation: TypedContractMethod<
    [wallet: AddressLike],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;

  totalAttestations: TypedContractMethod<[], [bigint], "view">;

  verifyHolding: TypedContractMethod<
    [
      wallet: AddressLike,
      attestationIndex: BigNumberish,
      leaf: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      blockNumber: BigNumberish,
      merkleRoot: BytesLike,
      totalValueGun: BigNumberish,
      itemCount: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [wallet: AddressLike, index: BigNumberish],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestationCount"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestAttestation"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAttestations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyHolding"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      attestationIndex: BigNumberish,
      leaf: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "PortfolioAttested"
  ): TypedContractEvent<
    PortfolioAttestedEvent.InputTuple,
    PortfolioAttestedEvent.OutputTuple,
    PortfolioAttestedEvent.OutputObject
  >;

  filters: {
    "PortfolioAttested(address,uint256,bytes32,uint256,uint16,uint256,string)": TypedContractEvent<
      PortfolioAttestedEvent.InputTuple,
      PortfolioAttestedEvent.OutputTuple,
      PortfolioAttestedEvent.OutputObject
    >;
    PortfolioAttested: TypedContractEvent<
      PortfolioAttestedEvent.InputTuple,
      PortfolioAttestedEvent.OutputTuple,
      PortfolioAttestedEvent.OutputObject
    >;
  };
}
