/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PortfolioAttestation__factory } from "./PortfolioAttestation__factory";
export { PortfolioAttestationV2__factory } from "./PortfolioAttestationV2__factory";
