/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PortfolioAttestation } from "./PortfolioAttestation";
export type { PortfolioAttestationV2 } from "./PortfolioAttestationV2";
