/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PortfolioAttestation {
  export type AttestationStruct = {
    blockNumber: BigNumberish;
    merkleRoot: BytesLike;
    totalValueGun: BigNumberish;
    itemCount: BigNumberish;
    timestamp: BigNumberish;
    metadataURI: string;
  };

  export type AttestationStructOutput = [
    blockNumber: bigint,
    merkleRoot: string,
    totalValueGun: bigint,
    itemCount: bigint,
    timestamp: bigint,
    metadataURI: string
  ] & {
    blockNumber: bigint;
    merkleRoot: string;
    totalValueGun: bigint;
    itemCount: bigint;
    timestamp: bigint;
    metadataURI: string;
  };

  export type PortfolioWalletStruct = {
    addr: AddressLike;
    status: BigNumberish;
    addedAt: BigNumberish;
  };

  export type PortfolioWalletStructOutput = [
    addr: string,
    status: bigint,
    addedAt: bigint
  ] & { addr: string; status: bigint; addedAt: bigint };
}

export interface PortfolioAttestationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "addWallet"
      | "attest"
      | "attestFee"
      | "getAttestation"
      | "getAttestationCount"
      | "getLatestAttestation"
      | "getPortfolioWalletCount"
      | "getPortfolioWallets"
      | "gsHandleOf"
      | "handleChangeFee"
      | "handleOwner"
      | "hasRegisteredHandle"
      | "initialize"
      | "initializeV2"
      | "owner"
      | "primaryOf"
      | "proxiableUUID"
      | "removeWallet"
      | "resolveHandle"
      | "setFee"
      | "setHandle"
      | "setHandleChangeFee"
      | "takeoverWallet"
      | "totalAttestations"
      | "totalFeesCollected"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "verifyHolding"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "HandleChanged"
      | "HandleFeeUpdated"
      | "HandleRegistered"
      | "Initialized"
      | "OwnerTransferred"
      | "PortfolioAttested"
      | "Upgraded"
      | "WalletAdded"
      | "WalletRemoved"
      | "WalletUpgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addWallet",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attest",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "attestFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPortfolioWalletCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPortfolioWallets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gsHandleOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleChangeFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRegisteredHandle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "primaryOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveHandle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setHandle", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setHandleChangeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "takeoverWallet",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAttestations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHolding",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "attestFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPortfolioWalletCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPortfolioWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gsHandleOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleChangeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRegisteredHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "primaryOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHandle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setHandleChangeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takeoverWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyHolding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleChangedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    oldHandle: string,
    newHandle: string
  ];
  export type OutputTuple = [
    wallet: string,
    oldHandle: string,
    newHandle: string
  ];
  export interface OutputObject {
    wallet: string;
    oldHandle: string;
    newHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, handle: string];
  export type OutputTuple = [wallet: string, handle: string];
  export interface OutputObject {
    wallet: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PortfolioAttestedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    attestationId: BigNumberish,
    merkleRoot: BytesLike,
    totalValueGun: BigNumberish,
    itemCount: BigNumberish,
    blockNumber: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    wallet: string,
    attestationId: bigint,
    merkleRoot: string,
    totalValueGun: bigint,
    itemCount: bigint,
    blockNumber: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    wallet: string;
    attestationId: bigint;
    merkleRoot: string;
    totalValueGun: bigint;
    itemCount: bigint;
    blockNumber: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletAddedEvent {
  export type InputTuple = [
    primary: AddressLike,
    wallet: AddressLike,
    status: BigNumberish
  ];
  export type OutputTuple = [primary: string, wallet: string, status: bigint];
  export interface OutputObject {
    primary: string;
    wallet: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletRemovedEvent {
  export type InputTuple = [primary: AddressLike, wallet: AddressLike];
  export type OutputTuple = [primary: string, wallet: string];
  export interface OutputObject {
    primary: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletUpgradedEvent {
  export type InputTuple = [
    primary: AddressLike,
    wallet: AddressLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    primary: string,
    wallet: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    primary: string;
    wallet: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PortfolioAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): PortfolioAttestation;
  waitForDeployment(): Promise<this>;

  interface: PortfolioAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addWallet: TypedContractMethod<
    [wallet: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  attest: TypedContractMethod<
    [
      wallet: AddressLike,
      blockNumber: BigNumberish,
      merkleRoot: BytesLike,
      totalValueGun: BigNumberish,
      itemCount: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "payable"
  >;

  attestFee: TypedContractMethod<[], [bigint], "view">;

  getAttestation: TypedContractMethod<
    [wallet: AddressLike, index: BigNumberish],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;

  getAttestationCount: TypedContractMethod<
    [wallet: AddressLike],
    [bigint],
    "view"
  >;

  getLatestAttestation: TypedContractMethod<
    [wallet: AddressLike],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;

  getPortfolioWalletCount: TypedContractMethod<
    [primary: AddressLike],
    [bigint],
    "view"
  >;

  getPortfolioWallets: TypedContractMethod<
    [primary: AddressLike],
    [PortfolioAttestation.PortfolioWalletStructOutput[]],
    "view"
  >;

  gsHandleOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  handleChangeFee: TypedContractMethod<[], [bigint], "view">;

  handleOwner: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  hasRegisteredHandle: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_attestFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  initializeV2: TypedContractMethod<
    [_handleChangeFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  primaryOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeWallet: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveHandle: TypedContractMethod<[handle: string], [string], "view">;

  setFee: TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;

  setHandle: TypedContractMethod<[handle: string], [void], "payable">;

  setHandleChangeFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  takeoverWallet: TypedContractMethod<
    [wallet: AddressLike, fromPrimary: AddressLike],
    [void],
    "nonpayable"
  >;

  totalAttestations: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verifyHolding: TypedContractMethod<
    [
      wallet: AddressLike,
      attestationIndex: BigNumberish,
      leaf: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addWallet"
  ): TypedContractMethod<
    [wallet: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      blockNumber: BigNumberish,
      merkleRoot: BytesLike,
      totalValueGun: BigNumberish,
      itemCount: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "attestFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [wallet: AddressLike, index: BigNumberish],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestationCount"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestAttestation"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [PortfolioAttestation.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPortfolioWalletCount"
  ): TypedContractMethod<[primary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPortfolioWallets"
  ): TypedContractMethod<
    [primary: AddressLike],
    [PortfolioAttestation.PortfolioWalletStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "gsHandleOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "handleChangeFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "handleOwner"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasRegisteredHandle"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_attestFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeV2"
  ): TypedContractMethod<
    [_handleChangeFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "primaryOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeWallet"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveHandle"
  ): TypedContractMethod<[handle: string], [string], "view">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHandle"
  ): TypedContractMethod<[handle: string], [void], "payable">;
  getFunction(
    nameOrSignature: "setHandleChangeFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "takeoverWallet"
  ): TypedContractMethod<
    [wallet: AddressLike, fromPrimary: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAttestations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verifyHolding"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      attestationIndex: BigNumberish,
      leaf: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HandleChanged"
  ): TypedContractEvent<
    HandleChangedEvent.InputTuple,
    HandleChangedEvent.OutputTuple,
    HandleChangedEvent.OutputObject
  >;
  getEvent(
    key: "HandleFeeUpdated"
  ): TypedContractEvent<
    HandleFeeUpdatedEvent.InputTuple,
    HandleFeeUpdatedEvent.OutputTuple,
    HandleFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HandleRegistered"
  ): TypedContractEvent<
    HandleRegisteredEvent.InputTuple,
    HandleRegisteredEvent.OutputTuple,
    HandleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerTransferred"
  ): TypedContractEvent<
    OwnerTransferredEvent.InputTuple,
    OwnerTransferredEvent.OutputTuple,
    OwnerTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PortfolioAttested"
  ): TypedContractEvent<
    PortfolioAttestedEvent.InputTuple,
    PortfolioAttestedEvent.OutputTuple,
    PortfolioAttestedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WalletAdded"
  ): TypedContractEvent<
    WalletAddedEvent.InputTuple,
    WalletAddedEvent.OutputTuple,
    WalletAddedEvent.OutputObject
  >;
  getEvent(
    key: "WalletRemoved"
  ): TypedContractEvent<
    WalletRemovedEvent.InputTuple,
    WalletRemovedEvent.OutputTuple,
    WalletRemovedEvent.OutputObject
  >;
  getEvent(
    key: "WalletUpgraded"
  ): TypedContractEvent<
    WalletUpgradedEvent.InputTuple,
    WalletUpgradedEvent.OutputTuple,
    WalletUpgradedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "HandleChanged(address,string,string)": TypedContractEvent<
      HandleChangedEvent.InputTuple,
      HandleChangedEvent.OutputTuple,
      HandleChangedEvent.OutputObject
    >;
    HandleChanged: TypedContractEvent<
      HandleChangedEvent.InputTuple,
      HandleChangedEvent.OutputTuple,
      HandleChangedEvent.OutputObject
    >;

    "HandleFeeUpdated(uint256,uint256)": TypedContractEvent<
      HandleFeeUpdatedEvent.InputTuple,
      HandleFeeUpdatedEvent.OutputTuple,
      HandleFeeUpdatedEvent.OutputObject
    >;
    HandleFeeUpdated: TypedContractEvent<
      HandleFeeUpdatedEvent.InputTuple,
      HandleFeeUpdatedEvent.OutputTuple,
      HandleFeeUpdatedEvent.OutputObject
    >;

    "HandleRegistered(address,string)": TypedContractEvent<
      HandleRegisteredEvent.InputTuple,
      HandleRegisteredEvent.OutputTuple,
      HandleRegisteredEvent.OutputObject
    >;
    HandleRegistered: TypedContractEvent<
      HandleRegisteredEvent.InputTuple,
      HandleRegisteredEvent.OutputTuple,
      HandleRegisteredEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnerTransferred(address,address)": TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;
    OwnerTransferred: TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;

    "PortfolioAttested(address,uint256,bytes32,uint256,uint16,uint256,string)": TypedContractEvent<
      PortfolioAttestedEvent.InputTuple,
      PortfolioAttestedEvent.OutputTuple,
      PortfolioAttestedEvent.OutputObject
    >;
    PortfolioAttested: TypedContractEvent<
      PortfolioAttestedEvent.InputTuple,
      PortfolioAttestedEvent.OutputTuple,
      PortfolioAttestedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WalletAdded(address,address,uint8)": TypedContractEvent<
      WalletAddedEvent.InputTuple,
      WalletAddedEvent.OutputTuple,
      WalletAddedEvent.OutputObject
    >;
    WalletAdded: TypedContractEvent<
      WalletAddedEvent.InputTuple,
      WalletAddedEvent.OutputTuple,
      WalletAddedEvent.OutputObject
    >;

    "WalletRemoved(address,address)": TypedContractEvent<
      WalletRemovedEvent.InputTuple,
      WalletRemovedEvent.OutputTuple,
      WalletRemovedEvent.OutputObject
    >;
    WalletRemoved: TypedContractEvent<
      WalletRemovedEvent.InputTuple,
      WalletRemovedEvent.OutputTuple,
      WalletRemovedEvent.OutputObject
    >;

    "WalletUpgraded(address,address,uint8,uint8)": TypedContractEvent<
      WalletUpgradedEvent.InputTuple,
      WalletUpgradedEvent.OutputTuple,
      WalletUpgradedEvent.OutputObject
    >;
    WalletUpgraded: TypedContractEvent<
      WalletUpgradedEvent.InputTuple,
      WalletUpgradedEvent.OutputTuple,
      WalletUpgradedEvent.OutputObject
    >;
  };
}
